import type { ToolMeta } from '@/types/tool'

/**
 * 工具注册表
 *
 * ✅ 添加新工具只需在此数组中追加一条记录：
 *   1. 在 src/views/tools/<category>/ 下创建工具组件
 *   2. 在此处添加工具元信息，component 使用 () => import('...') 懒加载
 *   3. 路由和首页展示会自动生成，无需手动修改其他文件
 */
export const tools: ToolMeta[] = [
  // 文本处理
  {
    name: 'text-diff',
    title: '文本差异对比',
    description: '左右对照、行内高亮、文件导入、忽略空白与大小写',
    category: 'text',
    icon: '⇄',
    keywords: ['diff', '差异', '对比', '比较', '文件'],
    path: '/text/diff',
    component: () => import('@/views/tools/text/TextDiff.vue'),
  },
  {
    name: 'text-batch',
    title: '文本批量处理',
    description: '按行去重、排序、去空行、命名转换与添加前后缀',
    category: 'text',
    icon: '≡',
    keywords: ['去重', '排序', '文本', '大小写', '驼峰'],
    path: '/text/batch',
    component: () => import('@/views/tools/text/TextBatch.vue'),
  },
  {
    name: 'text-length',
    title: '文本字数统计',
    description: '统计文本的字符数、单词数、行数等信息',
    category: 'text',
    icon: '🔢',
    keywords: ['字数', '统计', '长度', 'count', 'length'],
    path: '/text/length',
    component: () => import('@/views/tools/text/TextLength.vue'),
  },
  // 开发工具：常用工具优先
  {
    name: 'json-formatter',
    title: 'JSON 格式化',
    description: 'JSON 格式化、压缩、错误定位、转义与树形预览',
    category: 'dev',
    icon: '{ }',
    keywords: ['json', '格式化', '压缩', '校验', '转义', '树形', '美化'],
    path: '/dev/json-formatter',
    component: () => import('@/views/tools/dev/JsonFormatter.vue'),
  },
  {
    name: 'encoding-toolkit',
    title: '编码工具箱',
    description:
      'URL 解析、Base64 编解码、UUID 生成与 HTML / Unicode / 十六进制转义',
    category: 'dev',
    icon: '🔗',
    keywords: [
      'url',
      'query',
      '网址',
      '链接',
      '参数',
      '编码',
      '解码',
      '表单',
      'base64',
      'base64url',
      'uuid',
      'html',
      'unicode',
      'hex',
      '转义',
      '十六进制',
    ],
    path: '/dev/encoding-toolkit',
    component: () => import('@/views/tools/dev/EncodingToolkit.vue'),
  },
  {
    name: 'timestamp-converter',
    title: '时间工具箱',
    description: '时间戳转换、Cron 表达式、时区换算与实时世界时钟',
    category: 'dev',
    icon: '🕒',
    keywords: [
      '时间戳',
      '时间',
      '日期',
      '北京时间',
      '时区',
      '世界时钟',
      'timestamp',
      'timezone',
      'clock',
      'unix',
      'UTC',
      'cron',
      'crontab',
      '定时',
      '计划任务',
      '表达式',
      '执行时间',
    ],
    path: '/dev/timestamp-converter',
    component: () => import('@/views/tools/dev/TimeToolkit.vue'),
  },
  {
    name: 'regex-tester',
    title: '正则表达式测试',
    description: '实时匹配高亮、捕获组查看与替换预览',
    category: 'dev',
    icon: '.*',
    keywords: ['regex', 'regexp', '正则', '匹配', '替换'],
    path: '/dev/regex-tester',
    component: () => import('@/views/tools/dev/RegexTester.vue'),
  },
  {
    name: 'sql-formatter',
    title: 'SQL 格式化',
    description: 'MySQL、PostgreSQL 等方言排版，调整缩进和关键字大小写',
    category: 'dev',
    icon: '▤',
    keywords: ['sql', 'mysql', '数据库', '格式化'],
    path: '/dev/sql-formatter',
    component: () => import('@/views/tools/dev/SqlFormatter.vue'),
  },
  {
    name: 'jwt-viewer',
    title: 'JWT 解析',
    description: '本地解码 Header、Payload，查看声明与过期时间',
    category: 'dev',
    icon: '🔐',
    keywords: ['jwt', 'token', '令牌', '认证', '解码'],
    path: '/dev/jwt-viewer',
    component: () => import('@/views/tools/dev/JwtViewer.vue'),
  },
  {
    name: 'yaml-converter',
    title: 'JSON / YAML 互转',
    description: 'JSON 与 YAML 配置双向转换，检查语法与数据兼容性',
    category: 'dev',
    icon: '⇌',
    keywords: ['yaml', 'yml', 'json', '配置', '转换'],
    path: '/dev/yaml-converter',
    component: () => import('@/views/tools/dev/YamlConverter.vue'),
  },
  {
    name: 'json-types',
    title: 'JSON 转 TypeScript',
    description: '从接口样本推断 TypeScript 类型、联合类型和可选属性',
    category: 'dev',
    icon: 'TS',
    keywords: ['json', 'typescript', 'ts', '接口', '类型'],
    path: '/dev/json-types',
    component: () => import('@/views/tools/dev/JsonTypes.vue'),
  },
  {
    name: 'hash-calculator',
    title: '哈希计算',
    description: '文本与文件 SHA-256 / 384 / 512 / 1 摘要计算及校验',
    category: 'dev',
    icon: '#',
    keywords: ['hash', 'sha', '哈希', '摘要', '校验'],
    path: '/dev/hash-calculator',
    component: () => import('@/views/tools/dev/HashCalculator.vue'),
  },
  {
    name: 'radix-converter',
    title: '进制转换',
    description: '2–36 进制整数互转，支持超长整数与正负号',
    category: 'dev',
    icon: '01',
    keywords: ['进制', '二进制', '十六进制', 'bigint'],
    path: '/dev/radix-converter',
    component: () => import('@/views/tools/dev/RadixConverter.vue'),
  },
  {
    name: 'color-converter',
    title: '颜色转换与对比度',
    description: 'HEX、RGB、HSL 互转，文字背景预览与对比度检查',
    category: 'dev',
    icon: '🎨',
    keywords: ['颜色', 'color', 'rgb', 'hsl', 'hex', '对比度'],
    path: '/dev/color-converter',
    component: () => import('@/views/tools/dev/ColorConverter.vue'),
  },
  // 其他工具
  {
    name: 'hotpot-calculator',
    title: '朱富贵火锅菜价计算器',
    description: '火锅账单计算，支持人数、折扣、多种菜品盘价',
    category: 'other',
    icon: '🍲',
    keywords: ['火锅', '计算', '菜价', '账单', '朱富贵'],
    path: '/other/hotpot-calculator',
    component: () => import('@/views/tools/other/HotpotCalculator.vue'),
    standalone: true,
  },
]
