import type { ToolMeta } from '@/types/tool'

/** 首页、菜单和路由共用的工具注册表，按分类与显示顺序排列。 */
export const tools: ToolMeta[] = [
  {
    name: 'json-formatter',
    title: 'JSON 格式化',
    description: 'JSON 格式化、压缩、错误定位、转义与树形预览',
    category: 'encoding',
    icon: '{ }',
    keywords: ["json","格式化","压缩","校验","转义","树形","美化"],
    path: '/json',
    component: () => import('@/views/tools/dev/JsonFormatter.vue'),
  },
  {
    name: 'url-codec',
    title: 'URL 编解码',
    description: '普通与表单 URL 编码、解码，手动转换与复制',
    category: 'encoding',
    icon: '%',
    keywords: ["url","网址","链接","编码","解码","表单"],
    path: '/url',
    component: () => import('@/views/tools/dev/UrlCodec.vue'),
  },
  {
    name: 'timestamp-converter',
    title: '时间戳转换',
    description: '时间戳与北京时间双向转换，支持秒、毫秒和多种日期格式',
    category: 'encoding',
    icon: '🕒',
    keywords: ["timestamp","unix","时间","日期"],
    path: '/timestamp',
    component: () => import('@/views/tools/StandaloneTool.vue'),
  },
  {
    name: 'base64-codec',
    title: 'Base64 编解码',
    description: 'UTF-8 文本与 Base64、Base64URL 双向转换',
    category: 'encoding',
    icon: 'B64',
    keywords: ["base64","base64url","编码","解码"],
    path: '/base64',
    component: () => import('@/views/tools/StandaloneTool.vue'),
  },
  {
    name: 'image-base64',
    title: '图片 Base64',
    description: '图片与 Base64 双向转换，支持本地预览、复制和下载',
    category: 'encoding',
    icon: '🖼️',
    keywords: ['图片', 'image', 'base64', 'data url', '编码', '解码'],
    path: '/image-base64',
    component: () => import('@/views/tools/dev/ImageBase64.vue'),
  },
  {
    name: 'jwt-viewer',
    title: 'JWT 解析',
    description: '本地解码 Header、Payload，查看声明与过期时间',
    category: 'encoding',
    icon: 'JWT',
    keywords: ["jwt","token","令牌","认证","解码"],
    path: '/jwt',
    component: () => import('@/views/tools/dev/JwtViewer.vue'),
  },
  {
    name: 'uuid-generator',
    title: 'UUID 生成',
    description: '安全随机 UUID v4 批量生成，支持大小写与连字符',
    category: 'dev',
    icon: 'ID',
    keywords: ["uuid","随机","标识符","生成"],
    path: '/uuid',
    component: () => import('@/views/tools/StandaloneTool.vue'),
  },
  {
    name: 'cron-generator',
    title: 'Cron 表达式',
    description: '可视化生成与校验 Cron 表达式，预览未来执行时间',
    category: 'dev',
    icon: '⏱',
    keywords: ["cron","crontab","定时","计划任务","表达式"],
    path: '/cron',
    component: () => import('@/views/tools/StandaloneTool.vue'),
  },
  {
    name: 'http-status',
    title: 'HTTP 状态码速查',
    description: 'HTTP 状态码中英文搜索、分类筛选与常用响应说明',
    category: 'dev',
    icon: '📡',
    keywords: ['http', '状态码', 'status', '404', '响应', '请求'],
    path: '/http-status',
    component: () => import('@/views/tools/dev/HttpStatusLookup.vue'),
  },
  {
    name: 'timezone-converter',
    title: '时区转换',
    description: '跨时区换算，支持夏令时和自定义 UTC 偏移',
    category: 'dev',
    icon: '🌐',
    keywords: ["时区","timezone","utc","夏令时","时间"],
    path: '/timezone',
    component: () => import('@/views/tools/StandaloneTool.vue'),
  },
  {
    name: 'radix-converter',
    title: '进制转换',
    description: '2–36 进制整数互转，支持超长整数与正负号',
    category: 'dev',
    icon: '01',
    keywords: ["进制","二进制","十六进制","bigint"],
    path: '/radix',
    component: () => import('@/views/tools/dev/RadixConverter.vue'),
  },
  {
    name: 'color-converter',
    title: '颜色转换',
    description: 'HEX、RGB、HSL 互转，文字背景预览与对比度检查',
    category: 'dev',
    icon: '🎨',
    keywords: ["颜色","color","rgb","hsl","hex","对比度"],
    path: '/color',
    component: () => import('@/views/tools/dev/ColorConverter.vue'),
  },
  {
    name: 'sql-formatter',
    title: 'SQL 格式化',
    description: 'MySQL、PostgreSQL 等方言排版，调整缩进和关键字大小写',
    category: 'dev',
    icon: '▤',
    keywords: ["sql","mysql","数据库","格式化"],
    path: '/sql',
    component: () => import('@/views/tools/dev/SqlFormatter.vue'),
  },
  {
    name: 'text-diff',
    title: '文本差异对比',
    description: '左右对照、行内高亮、文件导入、忽略空白与大小写',
    category: 'text',
    icon: '⇄',
    keywords: ["diff","差异","对比","比较","文件"],
    path: '/text-diff',
    component: () => import('@/views/tools/text/TextDiff.vue'),
  },
  {
    name: 'text-length',
    title: '文本字数统计',
    description: '统计文本的字符数、单词数、行数等信息',
    category: 'text',
    icon: '🔢',
    keywords: ["字数","统计","长度","count","length"],
    path: '/text-length',
    component: () => import('@/views/tools/text/TextLength.vue'),
  },
  {
    name: 'regex-tester',
    title: '正则表达式测试',
    description: '点击测试匹配高亮、捕获组与替换预览',
    category: 'text',
    icon: '.*',
    keywords: ["regex","regexp","正则","匹配","替换"],
    path: '/regex',
    component: () => import('@/views/tools/dev/RegexTester.vue'),
  },
  {
    name: 'image-color-picker',
    title: '图片取色器',
    description: '上传或拖入图片，点击提取像素颜色，复制 HEX、RGB 与 HSL',
    category: 'image',
    icon: '🎯',
    keywords: ['图片', '取色', '吸管', 'image', 'color', 'picker', 'hex', 'rgb'],
    path: '/color-picker',
    component: () => import('@/views/tools/image/ImageColorPicker.vue'),
  },
  {
    name: 'excel-to-json',
    title: 'Excel 转 JSON',
    description: '本地读取 Excel，选择工作表、配置字段与数据类型，导出 JSON',
    category: 'data',
    icon: '▦',
    keywords: ['excel', 'xlsx', 'xls', 'json', '表格', '工作表', '数据', '转换'],
    path: '/excel-to-json',
    component: () => import('@/views/tools/data/ExcelToJson.vue'),
  },
  {
    name: 'hash-calculator',
    title: '哈希计算',
    description: '文本与文件 SHA-256 / 384 / 512 / 1 摘要计算及校验',
    category: 'encrypt',
    icon: '#',
    keywords: ["hash","sha","哈希","摘要","校验"],
    path: '/hash',
    component: () => import('@/views/tools/dev/HashCalculator.vue'),
  },
  {
    name: 'password-generator',
    title: '随机密码生成',
    description: '安全随机密码，支持长度、字符类型、批量生成和复制',
    category: 'encrypt',
    icon: '🔑',
    keywords: ['密码', 'password', '随机', '生成', '安全'],
    path: '/password',
    component: () => import('@/views/tools/dev/PasswordGenerator.vue'),
  },
  {
    name: 'world-clock',
    title: '世界时钟',
    description: '实时查看世界各地的日期、时间和时差',
    category: 'life',
    icon: '🌍',
    keywords: ["时钟","世界","clock","时间","时区"],
    path: '/clock',
    component: () => import('@/views/tools/StandaloneTool.vue'),
  },
  {
    name: 'loan-calculator',
    title: '贷款计算器',
    description: '消费贷、经营贷自定义测算，支持等额本息、等额本金和还款明细',
    category: 'life',
    icon: '💰',
    keywords: ['贷款', '消费贷', '经营贷', '利率', '利息', '月供', '等额本息', '等额本金', 'loan'],
    path: '/loan',
    component: () => import('@/views/tools/life/LoanCalculator.vue'),
  },
  {
    name: 'car-loan-calculator',
    title: '车贷计算器',
    description: '固定手续费汽车分期，支持贷五免二、全期免手续费及落地成本明细',
    category: 'life',
    icon: '🚗',
    keywords: ['车贷', '汽车', '买车', '首付', '免息', '贷五免二', '手续费', '月供', '落地价', 'car', 'loan'],
    path: '/car-loan',
    component: () => import('@/views/tools/life/CarLoanCalculator.vue'),
  },
  {
    name: 'mortgage-calculator',
    title: '房贷计算器',
    description: '等额本息与等额本金房贷测算，查看月供、每月递减金额和还款明细',
    category: 'life',
    icon: '🏠',
    keywords: ['房贷', '住房', '按揭', '月供', '利息', '等额本息', '等额本金', 'mortgage'],
    path: '/mortgage',
    component: () => import('@/views/tools/life/MortgageCalculator.vue'),
  },
  {
    name: 'income-tax-calculator',
    title: '个税计算器',
    description: '工资累计预扣与年度综合所得汇算测算，查看到手收入、补退税及税率表',
    category: 'life',
    icon: '🧾',
    keywords: ['个税', '工资', '税后', '五险一金', '专项附加扣除', '累计预扣', '年度汇算', '退税', 'tax'],
    path: '/income-tax',
    component: () => import('@/views/tools/life/IncomeTaxCalculator.vue'),
  },
  {
    name: 'hotpot-calculator',
    title: '朱富贵火锅菜价计算器',
    description: '火锅账单计算，支持人数、折扣、多种菜品盘价',
    category: 'life',
    icon: '🍲',
    keywords: ["火锅","计算","菜价","账单","朱富贵"],
    path: '/zfg',
    component: () => import('@/views/tools/other/HotpotCalculator.vue'),
    standalone: true,
  },
]
