// IANA tzdb 2026e zone.tab: https://data.iana.org/time-zones/tzdb/zone.tab
// Chinese names and aliases: Unicode CLDR 48 (common/main/zh.xml, en.xml, bcp47/timezone.xml).
// Copyright Unicode, Inc. Distributed under public/licenses/Unicode-3.0.txt.
// Fields: IANA ID, country code, Chinese country name, English country name, Chinese city, equivalent aliases.
export const worldTimeZoneData: readonly (readonly [string, string, string, string, string, string])[] = [
  ["Europe/Andorra","AD","安道尔","Andorra","安道尔",""],
  ["Asia/Dubai","AE","阿拉伯联合酋长国","United Arab Emirates","迪拜",""],
  ["Asia/Kabul","AF","阿富汗","Afghanistan","喀布尔",""],
  ["America/Antigua","AG","安提瓜和巴布达","Antigua & Barbuda","安提瓜",""],
  ["America/Anguilla","AI","安圭拉","Anguilla","安圭拉",""],
  ["Europe/Tirane","AL","阿尔巴尼亚","Albania","地拉那",""],
  ["Asia/Yerevan","AM","亚美尼亚","Armenia","埃里温",""],
  ["Africa/Luanda","AO","安哥拉","Angola","罗安达",""],
  ["Antarctica/McMurdo","AQ","南极洲","Antarctica","麦克默多","Antarctica/South_Pole"],
  ["Antarctica/Casey","AQ","南极洲","Antarctica","卡塞",""],
  ["Antarctica/Davis","AQ","南极洲","Antarctica","戴维斯",""],
  ["Antarctica/DumontDUrville","AQ","南极洲","Antarctica","迪蒙·迪维尔",""],
  ["Antarctica/Mawson","AQ","南极洲","Antarctica","莫森",""],
  ["Antarctica/Palmer","AQ","南极洲","Antarctica","帕尔默",""],
  ["Antarctica/Rothera","AQ","南极洲","Antarctica","罗瑟拉",""],
  ["Antarctica/Syowa","AQ","南极洲","Antarctica","昭和",""],
  ["Antarctica/Troll","AQ","南极洲","Antarctica","特罗尔",""],
  ["Antarctica/Vostok","AQ","南极洲","Antarctica","沃斯托克",""],
  ["America/Argentina/Buenos_Aires","AR","阿根廷","Argentina","布宜诺斯艾利斯","America/Buenos_Aires"],
  ["America/Argentina/Cordoba","AR","阿根廷","Argentina","科尔多瓦","America/Cordoba America/Rosario"],
  ["America/Argentina/Salta","AR","阿根廷","Argentina","萨尔塔",""],
  ["America/Argentina/Jujuy","AR","阿根廷","Argentina","胡胡伊","America/Jujuy"],
  ["America/Argentina/Tucuman","AR","阿根廷","Argentina","图库曼",""],
  ["America/Argentina/Catamarca","AR","阿根廷","Argentina","卡塔马卡","America/Catamarca America/Argentina/ComodRivadavia"],
  ["America/Argentina/La_Rioja","AR","阿根廷","Argentina","拉里奥哈",""],
  ["America/Argentina/San_Juan","AR","阿根廷","Argentina","圣胡安",""],
  ["America/Argentina/Mendoza","AR","阿根廷","Argentina","门多萨","America/Mendoza"],
  ["America/Argentina/San_Luis","AR","阿根廷","Argentina","圣路易斯",""],
  ["America/Argentina/Rio_Gallegos","AR","阿根廷","Argentina","里奥加耶戈斯",""],
  ["America/Argentina/Ushuaia","AR","阿根廷","Argentina","乌斯怀亚",""],
  ["Pacific/Pago_Pago","AS","美属萨摩亚","American Samoa","帕果帕果","Pacific/Samoa US/Samoa"],
  ["Europe/Vienna","AT","奥地利","Austria","维也纳",""],
  ["Australia/Lord_Howe","AU","澳大利亚","Australia","豪勋爵岛","Australia/LHI"],
  ["Antarctica/Macquarie","AU","澳大利亚","Australia","麦夸里岛",""],
  ["Australia/Hobart","AU","澳大利亚","Australia","霍巴特","Australia/Tasmania Australia/Currie"],
  ["Australia/Melbourne","AU","澳大利亚","Australia","墨尔本","Australia/Victoria"],
  ["Australia/Sydney","AU","澳大利亚","Australia","悉尼","Australia/ACT Australia/Canberra Australia/NSW"],
  ["Australia/Broken_Hill","AU","澳大利亚","Australia","布罗肯希尔","Australia/Yancowinna"],
  ["Australia/Brisbane","AU","澳大利亚","Australia","布里斯班","Australia/Queensland"],
  ["Australia/Lindeman","AU","澳大利亚","Australia","林德曼",""],
  ["Australia/Adelaide","AU","澳大利亚","Australia","阿德莱德","Australia/South"],
  ["Australia/Darwin","AU","澳大利亚","Australia","达尔文","Australia/North"],
  ["Australia/Perth","AU","澳大利亚","Australia","珀斯","Australia/West"],
  ["Australia/Eucla","AU","澳大利亚","Australia","尤克拉",""],
  ["America/Aruba","AW","阿鲁巴","Aruba","阿鲁巴",""],
  ["Europe/Mariehamn","AX","奥兰群岛","Åland Islands","玛丽港",""],
  ["Asia/Baku","AZ","阿塞拜疆","Azerbaijan","巴库",""],
  ["Europe/Sarajevo","BA","波斯尼亚和黑塞哥维那","Bosnia & Herzegovina","萨拉热窝",""],
  ["America/Barbados","BB","巴巴多斯","Barbados","巴巴多斯",""],
  ["Asia/Dhaka","BD","孟加拉国","Bangladesh","达卡","Asia/Dacca"],
  ["Europe/Brussels","BE","比利时","Belgium","布鲁塞尔","CET MET"],
  ["Africa/Ouagadougou","BF","布基纳法索","Burkina Faso","瓦加杜古",""],
  ["Europe/Sofia","BG","保加利亚","Bulgaria","索非亚",""],
  ["Asia/Bahrain","BH","巴林","Bahrain","巴林",""],
  ["Africa/Bujumbura","BI","布隆迪","Burundi","布琼布拉",""],
  ["Africa/Porto-Novo","BJ","贝宁","Benin","波多诺伏",""],
  ["America/St_Barthelemy","BL","圣巴泰勒米","St. Barthélemy","圣巴泰勒米岛",""],
  ["Atlantic/Bermuda","BM","百慕大","Bermuda","百慕大",""],
  ["Asia/Brunei","BN","文莱","Brunei","文莱",""],
  ["America/La_Paz","BO","玻利维亚","Bolivia","拉巴斯",""],
  ["America/Kralendijk","BQ","荷属加勒比区","Caribbean Netherlands","克拉伦代克",""],
  ["America/Noronha","BR","巴西","Brazil","洛罗尼亚","Brazil/DeNoronha"],
  ["America/Belem","BR","巴西","Brazil","贝伦",""],
  ["America/Fortaleza","BR","巴西","Brazil","福塔雷萨",""],
  ["America/Recife","BR","巴西","Brazil","累西腓",""],
  ["America/Araguaina","BR","巴西","Brazil","阿拉瓜伊纳",""],
  ["America/Maceio","BR","巴西","Brazil","马塞约",""],
  ["America/Bahia","BR","巴西","Brazil","巴伊亚",""],
  ["America/Sao_Paulo","BR","巴西","Brazil","圣保罗","Brazil/East"],
  ["America/Campo_Grande","BR","巴西","Brazil","大坎普",""],
  ["America/Cuiaba","BR","巴西","Brazil","库亚巴",""],
  ["America/Santarem","BR","巴西","Brazil","圣塔伦",""],
  ["America/Porto_Velho","BR","巴西","Brazil","波多韦柳",""],
  ["America/Boa_Vista","BR","巴西","Brazil","博阿维斯塔",""],
  ["America/Manaus","BR","巴西","Brazil","马瑙斯","Brazil/West"],
  ["America/Eirunepe","BR","巴西","Brazil","依伦尼贝",""],
  ["America/Rio_Branco","BR","巴西","Brazil","里奥布郎库","America/Porto_Acre Brazil/Acre"],
  ["America/Nassau","BS","巴哈马","Bahamas","拿骚",""],
  ["Asia/Thimphu","BT","不丹","Bhutan","廷布","Asia/Thimbu"],
  ["Africa/Gaborone","BW","博茨瓦纳","Botswana","哈博罗内",""],
  ["Europe/Minsk","BY","白俄罗斯","Belarus","明斯克",""],
  ["America/Belize","BZ","伯利兹","Belize","伯利兹",""],
  ["America/St_Johns","CA","加拿大","Canada","圣约翰斯","Canada/Newfoundland"],
  ["America/Halifax","CA","加拿大","Canada","哈利法克斯","Canada/Atlantic"],
  ["America/Glace_Bay","CA","加拿大","Canada","格莱斯贝",""],
  ["America/Moncton","CA","加拿大","Canada","蒙克顿",""],
  ["America/Goose_Bay","CA","加拿大","Canada","古斯湾",""],
  ["America/Blanc-Sablon","CA","加拿大","Canada","布兰克萨布隆",""],
  ["America/Toronto","CA","加拿大","Canada","多伦多","America/Montreal Canada/Eastern America/Nipigon America/Thunder_Bay"],
  ["America/Iqaluit","CA","加拿大","Canada","伊魁特","America/Pangnirtung"],
  ["America/Atikokan","CA","加拿大","Canada","阿蒂科肯","America/Coral_Harbour"],
  ["America/Winnipeg","CA","加拿大","Canada","温尼伯","Canada/Central America/Rainy_River"],
  ["America/Resolute","CA","加拿大","Canada","雷索卢特",""],
  ["America/Rankin_Inlet","CA","加拿大","Canada","兰今湾",""],
  ["America/Regina","CA","加拿大","Canada","里贾纳","Canada/East-Saskatchewan Canada/Saskatchewan"],
  ["America/Swift_Current","CA","加拿大","Canada","斯威夫特卡伦特",""],
  ["America/Edmonton","CA","加拿大","Canada","埃德蒙顿","Canada/Mountain America/Yellowknife"],
  ["America/Cambridge_Bay","CA","加拿大","Canada","剑桥湾",""],
  ["America/Inuvik","CA","加拿大","Canada","伊努维克",""],
  ["America/Vancouver","CA","加拿大","Canada","温哥华","Canada/Pacific"],
  ["America/Creston","CA","加拿大","Canada","克雷斯顿",""],
  ["America/Dawson_Creek","CA","加拿大","Canada","道森克里克",""],
  ["America/Fort_Nelson","CA","加拿大","Canada","纳尔逊堡",""],
  ["America/Whitehorse","CA","加拿大","Canada","怀特霍斯","Canada/Yukon"],
  ["America/Dawson","CA","加拿大","Canada","道森",""],
  ["Indian/Cocos","CC","科科斯（基林）群岛","Cocos (Keeling) Islands","可可斯",""],
  ["Africa/Kinshasa","CD","刚果（金）","Congo - Kinshasa","金沙萨",""],
  ["Africa/Lubumbashi","CD","刚果（金）","Congo - Kinshasa","卢本巴希",""],
  ["Africa/Bangui","CF","中非共和国","Central African Republic","班吉",""],
  ["Africa/Brazzaville","CG","刚果（布）","Congo - Brazzaville","布拉柴维尔",""],
  ["Europe/Zurich","CH","瑞士","Switzerland","苏黎世",""],
  ["Africa/Abidjan","CI","科特迪瓦","Côte d’Ivoire","阿比让",""],
  ["Pacific/Rarotonga","CK","库克群岛","Cook Islands","拉罗汤加",""],
  ["America/Santiago","CL","智利","Chile","圣地亚哥","Chile/Continental"],
  ["America/Coyhaique","CL","智利","Chile","科伊艾克",""],
  ["America/Punta_Arenas","CL","智利","Chile","蓬塔阿雷纳斯",""],
  ["Pacific/Easter","CL","智利","Chile","复活节岛","Chile/EasterIsland"],
  ["Africa/Douala","CM","喀麦隆","Cameroon","杜阿拉",""],
  ["Asia/Shanghai","CN","中国","China","上海","Asia/Chongqing Asia/Chungking Asia/Harbin PRC"],
  ["Asia/Urumqi","CN","中国","China","乌鲁木齐","Asia/Kashgar"],
  ["America/Bogota","CO","哥伦比亚","Colombia","波哥大",""],
  ["America/Costa_Rica","CR","哥斯达黎加","Costa Rica","哥斯达黎加",""],
  ["America/Havana","CU","古巴","Cuba","哈瓦那","Cuba"],
  ["Atlantic/Cape_Verde","CV","佛得角","Cape Verde","佛得角",""],
  ["America/Curacao","CW","库拉索","Curaçao","库拉索",""],
  ["Indian/Christmas","CX","圣诞岛","Christmas Island","圣诞岛",""],
  ["Asia/Nicosia","CY","塞浦路斯","Cyprus","尼科西亚","Europe/Nicosia"],
  ["Asia/Famagusta","CY","塞浦路斯","Cyprus","法马古斯塔",""],
  ["Europe/Prague","CZ","捷克","Czechia","布拉格",""],
  ["Europe/Berlin","DE","德国","Germany","柏林",""],
  ["Europe/Busingen","DE","德国","Germany","布辛根",""],
  ["Africa/Djibouti","DJ","吉布提","Djibouti","吉布提",""],
  ["Europe/Copenhagen","DK","丹麦","Denmark","哥本哈根",""],
  ["America/Dominica","DM","多米尼克","Dominica","多米尼加",""],
  ["America/Santo_Domingo","DO","多米尼加共和国","Dominican Republic","圣多明各",""],
  ["Africa/Algiers","DZ","阿尔及利亚","Algeria","阿尔及尔",""],
  ["America/Guayaquil","EC","厄瓜多尔","Ecuador","瓜亚基尔",""],
  ["Pacific/Galapagos","EC","厄瓜多尔","Ecuador","科隆群岛",""],
  ["Europe/Tallinn","EE","爱沙尼亚","Estonia","塔林",""],
  ["Africa/Cairo","EG","埃及","Egypt","开罗","Egypt"],
  ["Africa/El_Aaiun","EH","西撒哈拉","Western Sahara","阿尤恩",""],
  ["Africa/Asmara","ER","厄立特里亚","Eritrea","阿斯马拉","Africa/Asmera"],
  ["Europe/Madrid","ES","西班牙","Spain","马德里",""],
  ["Africa/Ceuta","ES","西班牙","Spain","休达",""],
  ["Atlantic/Canary","ES","西班牙","Spain","加那利",""],
  ["Africa/Addis_Ababa","ET","埃塞俄比亚","Ethiopia","亚的斯亚贝巴",""],
  ["Europe/Helsinki","FI","芬兰","Finland","赫尔辛基",""],
  ["Pacific/Fiji","FJ","斐济","Fiji","斐济",""],
  ["Atlantic/Stanley","FK","福克兰群岛","Falkland Islands","斯坦利",""],
  ["Pacific/Chuuk","FM","密克罗尼西亚","Micronesia","特鲁克群岛","Pacific/Truk Pacific/Yap"],
  ["Pacific/Pohnpei","FM","密克罗尼西亚","Micronesia","波纳佩岛","Pacific/Ponape"],
  ["Pacific/Kosrae","FM","密克罗尼西亚","Micronesia","库赛埃",""],
  ["Atlantic/Faroe","FO","法罗群岛","Faroe Islands","法罗","Atlantic/Faeroe"],
  ["Europe/Paris","FR","法国","France","巴黎",""],
  ["Africa/Libreville","GA","加蓬","Gabon","利伯维尔",""],
  ["Europe/London","GB","英国","United Kingdom","伦敦","Europe/Belfast GB GB-Eire"],
  ["America/Grenada","GD","格林纳达","Grenada","格林纳达",""],
  ["Asia/Tbilisi","GE","格鲁吉亚","Georgia","第比利斯",""],
  ["America/Cayenne","GF","法属圭亚那","French Guiana","卡宴",""],
  ["Europe/Guernsey","GG","根西岛","Guernsey","根西岛",""],
  ["Africa/Accra","GH","加纳","Ghana","阿克拉",""],
  ["Europe/Gibraltar","GI","直布罗陀","Gibraltar","直布罗陀",""],
  ["America/Nuuk","GL","格陵兰","Greenland","努克","America/Godthab"],
  ["America/Danmarkshavn","GL","格陵兰","Greenland","丹马沙文",""],
  ["America/Scoresbysund","GL","格陵兰","Greenland","斯科列斯比桑德",""],
  ["America/Thule","GL","格陵兰","Greenland","图勒",""],
  ["Africa/Banjul","GM","冈比亚","Gambia","班珠尔",""],
  ["Africa/Conakry","GN","几内亚","Guinea","科纳克里",""],
  ["America/Guadeloupe","GP","瓜德罗普","Guadeloupe","瓜德罗普",""],
  ["Africa/Malabo","GQ","赤道几内亚","Equatorial Guinea","马拉博",""],
  ["Europe/Athens","GR","希腊","Greece","雅典","EET"],
  ["Atlantic/South_Georgia","GS","南乔治亚和南桑威奇群岛","South Georgia & South Sandwich Islands","南乔治亚",""],
  ["America/Guatemala","GT","危地马拉","Guatemala","危地马拉",""],
  ["Pacific/Guam","GU","关岛","Guam","关岛",""],
  ["Africa/Bissau","GW","几内亚比绍","Guinea-Bissau","比绍",""],
  ["America/Guyana","GY","圭亚那","Guyana","圭亚那",""],
  ["Asia/Hong_Kong","HK","中国香港特别行政区","Hong Kong SAR China","香港","Hongkong"],
  ["America/Tegucigalpa","HN","洪都拉斯","Honduras","特古西加尔巴",""],
  ["Europe/Zagreb","HR","克罗地亚","Croatia","萨格勒布",""],
  ["America/Port-au-Prince","HT","海地","Haiti","太子港",""],
  ["Europe/Budapest","HU","匈牙利","Hungary","布达佩斯",""],
  ["Asia/Jakarta","ID","印度尼西亚","Indonesia","雅加达",""],
  ["Asia/Pontianak","ID","印度尼西亚","Indonesia","坤甸",""],
  ["Asia/Makassar","ID","印度尼西亚","Indonesia","望加锡","Asia/Ujung_Pandang"],
  ["Asia/Jayapura","ID","印度尼西亚","Indonesia","查亚普拉",""],
  ["Europe/Dublin","IE","爱尔兰","Ireland","都柏林","Eire"],
  ["Asia/Jerusalem","IL","以色列","Israel","耶路撒冷","Asia/Tel_Aviv Israel"],
  ["Europe/Isle_of_Man","IM","马恩岛","Isle of Man","马恩岛",""],
  ["Asia/Kolkata","IN","印度","India","加尔各答","Asia/Calcutta"],
  ["Indian/Chagos","IO","英属印度洋领地","British Indian Ocean Territory","查戈斯",""],
  ["Asia/Baghdad","IQ","伊拉克","Iraq","巴格达",""],
  ["Asia/Tehran","IR","伊朗","Iran","德黑兰","Iran"],
  ["Atlantic/Reykjavik","IS","冰岛","Iceland","雷克雅未克","Iceland"],
  ["Europe/Rome","IT","意大利","Italy","罗马",""],
  ["Europe/Jersey","JE","泽西岛","Jersey","泽西岛",""],
  ["America/Jamaica","JM","牙买加","Jamaica","牙买加","Jamaica"],
  ["Asia/Amman","JO","约旦","Jordan","安曼",""],
  ["Asia/Tokyo","JP","日本","Japan","东京","Japan"],
  ["Africa/Nairobi","KE","肯尼亚","Kenya","内罗毕",""],
  ["Asia/Bishkek","KG","吉尔吉斯斯坦","Kyrgyzstan","比什凯克",""],
  ["Asia/Phnom_Penh","KH","柬埔寨","Cambodia","金边",""],
  ["Pacific/Tarawa","KI","基里巴斯","Kiribati","塔拉瓦",""],
  ["Pacific/Kanton","KI","基里巴斯","Kiribati","坎顿岛","Pacific/Enderbury"],
  ["Pacific/Kiritimati","KI","基里巴斯","Kiribati","基里地马地岛",""],
  ["Indian/Comoro","KM","科摩罗","Comoros","科摩罗",""],
  ["America/St_Kitts","KN","圣基茨和尼维斯","St. Kitts & Nevis","圣基茨",""],
  ["Asia/Pyongyang","KP","朝鲜","North Korea","平壤",""],
  ["Asia/Seoul","KR","韩国","South Korea","首尔","ROK"],
  ["Asia/Kuwait","KW","科威特","Kuwait","科威特",""],
  ["America/Cayman","KY","开曼群岛","Cayman Islands","开曼",""],
  ["Asia/Almaty","KZ","哈萨克斯坦","Kazakhstan","阿拉木图",""],
  ["Asia/Qyzylorda","KZ","哈萨克斯坦","Kazakhstan","克孜洛尔达",""],
  ["Asia/Qostanay","KZ","哈萨克斯坦","Kazakhstan","库斯塔奈",""],
  ["Asia/Aqtobe","KZ","哈萨克斯坦","Kazakhstan","阿克托别",""],
  ["Asia/Aqtau","KZ","哈萨克斯坦","Kazakhstan","阿克套",""],
  ["Asia/Atyrau","KZ","哈萨克斯坦","Kazakhstan","阿特劳",""],
  ["Asia/Oral","KZ","哈萨克斯坦","Kazakhstan","乌拉尔",""],
  ["Asia/Vientiane","LA","老挝","Laos","万象",""],
  ["Asia/Beirut","LB","黎巴嫩","Lebanon","贝鲁特",""],
  ["America/St_Lucia","LC","圣卢西亚","St. Lucia","圣卢西亚",""],
  ["Europe/Vaduz","LI","列支敦士登","Liechtenstein","瓦杜兹",""],
  ["Asia/Colombo","LK","斯里兰卡","Sri Lanka","科伦坡",""],
  ["Africa/Monrovia","LR","利比里亚","Liberia","蒙罗维亚",""],
  ["Africa/Maseru","LS","莱索托","Lesotho","马塞卢",""],
  ["Europe/Vilnius","LT","立陶宛","Lithuania","维尔纽斯",""],
  ["Europe/Luxembourg","LU","卢森堡","Luxembourg","卢森堡",""],
  ["Europe/Riga","LV","拉脱维亚","Latvia","里加",""],
  ["Africa/Tripoli","LY","利比亚","Libya","的黎波里","Libya"],
  ["Africa/Casablanca","MA","摩洛哥","Morocco","卡萨布兰卡",""],
  ["Europe/Monaco","MC","摩纳哥","Monaco","摩纳哥",""],
  ["Europe/Chisinau","MD","摩尔多瓦","Moldova","基希讷乌","Europe/Tiraspol"],
  ["Europe/Podgorica","ME","黑山","Montenegro","波德戈里察",""],
  ["America/Marigot","MF","法属圣马丁","St. Martin","马里戈特",""],
  ["Indian/Antananarivo","MG","马达加斯加","Madagascar","安塔那那利佛",""],
  ["Pacific/Majuro","MH","马绍尔群岛","Marshall Islands","马朱罗",""],
  ["Pacific/Kwajalein","MH","马绍尔群岛","Marshall Islands","夸贾林","Kwajalein"],
  ["Europe/Skopje","MK","北马其顿","North Macedonia","斯科普里",""],
  ["Africa/Bamako","ML","马里","Mali","巴马科","Africa/Timbuktu"],
  ["Asia/Yangon","MM","缅甸","Myanmar (Burma)","仰光","Asia/Rangoon"],
  ["Asia/Ulaanbaatar","MN","蒙古","Mongolia","乌兰巴托","Asia/Ulan_Bator Asia/Choibalsan"],
  ["Asia/Hovd","MN","蒙古","Mongolia","科布多",""],
  ["Asia/Macau","MO","中国澳门特别行政区","Macao SAR China","澳门","Asia/Macao"],
  ["Pacific/Saipan","MP","北马里亚纳群岛","Northern Mariana Islands","塞班",""],
  ["America/Martinique","MQ","马提尼克","Martinique","马提尼克",""],
  ["Africa/Nouakchott","MR","毛里塔尼亚","Mauritania","努瓦克肖特",""],
  ["America/Montserrat","MS","蒙特塞拉特","Montserrat","蒙特塞拉特",""],
  ["Europe/Malta","MT","马耳他","Malta","马耳他",""],
  ["Indian/Mauritius","MU","毛里求斯","Mauritius","毛里求斯",""],
  ["Indian/Maldives","MV","马尔代夫","Maldives","马尔代夫",""],
  ["Africa/Blantyre","MW","马拉维","Malawi","布兰太尔",""],
  ["America/Mexico_City","MX","墨西哥","Mexico","墨西哥城","Mexico/General"],
  ["America/Cancun","MX","墨西哥","Mexico","坎昆",""],
  ["America/Merida","MX","墨西哥","Mexico","梅里达",""],
  ["America/Monterrey","MX","墨西哥","Mexico","蒙特雷",""],
  ["America/Matamoros","MX","墨西哥","Mexico","马塔莫罗斯",""],
  ["America/Chihuahua","MX","墨西哥","Mexico","奇瓦瓦",""],
  ["America/Ciudad_Juarez","MX","墨西哥","Mexico","华雷斯城",""],
  ["America/Ojinaga","MX","墨西哥","Mexico","奥希纳加",""],
  ["America/Mazatlan","MX","墨西哥","Mexico","马萨特兰","Mexico/BajaSur"],
  ["America/Bahia_Banderas","MX","墨西哥","Mexico","巴伊亚班德拉斯",""],
  ["America/Hermosillo","MX","墨西哥","Mexico","埃莫西约",""],
  ["America/Tijuana","MX","墨西哥","Mexico","蒂华纳","America/Ensenada Mexico/BajaNorte America/Santa_Isabel"],
  ["Asia/Kuala_Lumpur","MY","马来西亚","Malaysia","吉隆坡",""],
  ["Asia/Kuching","MY","马来西亚","Malaysia","古晋",""],
  ["Africa/Maputo","MZ","莫桑比克","Mozambique","马普托",""],
  ["Africa/Windhoek","NA","纳米比亚","Namibia","温得和克",""],
  ["Pacific/Noumea","NC","新喀里多尼亚","New Caledonia","努美阿",""],
  ["Africa/Niamey","NE","尼日尔","Niger","尼亚美",""],
  ["Pacific/Norfolk","NF","诺福克岛","Norfolk Island","诺福克",""],
  ["Africa/Lagos","NG","尼日利亚","Nigeria","拉各斯",""],
  ["America/Managua","NI","尼加拉瓜","Nicaragua","马那瓜",""],
  ["Europe/Amsterdam","NL","荷兰","Netherlands","阿姆斯特丹",""],
  ["Europe/Oslo","NO","挪威","Norway","奥斯陆",""],
  ["Asia/Kathmandu","NP","尼泊尔","Nepal","加德满都","Asia/Katmandu"],
  ["Pacific/Nauru","NR","瑙鲁","Nauru","瑙鲁",""],
  ["Pacific/Niue","NU","纽埃","Niue","纽埃",""],
  ["Pacific/Auckland","NZ","新西兰","New Zealand","奥克兰","NZ"],
  ["Pacific/Chatham","NZ","新西兰","New Zealand","查塔姆","NZ-CHAT"],
  ["Asia/Muscat","OM","阿曼","Oman","马斯喀特",""],
  ["America/Panama","PA","巴拿马","Panama","巴拿马","EST"],
  ["America/Lima","PE","秘鲁","Peru","利马",""],
  ["Pacific/Tahiti","PF","法属波利尼西亚","French Polynesia","塔希提",""],
  ["Pacific/Marquesas","PF","法属波利尼西亚","French Polynesia","马克萨斯",""],
  ["Pacific/Gambier","PF","法属波利尼西亚","French Polynesia","甘比尔",""],
  ["Pacific/Port_Moresby","PG","巴布亚新几内亚","Papua New Guinea","莫尔兹比港",""],
  ["Pacific/Bougainville","PG","巴布亚新几内亚","Papua New Guinea","布干维尔",""],
  ["Asia/Manila","PH","菲律宾","Philippines","马尼拉",""],
  ["Asia/Karachi","PK","巴基斯坦","Pakistan","卡拉奇",""],
  ["Europe/Warsaw","PL","波兰","Poland","华沙","Poland"],
  ["America/Miquelon","PM","圣皮埃尔和密克隆群岛","St. Pierre & Miquelon","密克隆",""],
  ["Pacific/Pitcairn","PN","皮特凯恩群岛","Pitcairn Islands","皮特凯恩",""],
  ["America/Puerto_Rico","PR","波多黎各","Puerto Rico","波多黎各",""],
  ["Asia/Gaza","PS","巴勒斯坦领土","Palestinian Territories","加沙",""],
  ["Asia/Hebron","PS","巴勒斯坦领土","Palestinian Territories","希伯伦",""],
  ["Europe/Lisbon","PT","葡萄牙","Portugal","里斯本","Portugal WET"],
  ["Atlantic/Madeira","PT","葡萄牙","Portugal","马德拉",""],
  ["Atlantic/Azores","PT","葡萄牙","Portugal","亚速尔群岛",""],
  ["Pacific/Palau","PW","帕劳","Palau","帕劳",""],
  ["America/Asuncion","PY","巴拉圭","Paraguay","亚松森",""],
  ["Asia/Qatar","QA","卡塔尔","Qatar","卡塔尔",""],
  ["Indian/Reunion","RE","留尼汪","Réunion","留尼汪",""],
  ["Europe/Bucharest","RO","罗马尼亚","Romania","布加勒斯特",""],
  ["Europe/Belgrade","RS","塞尔维亚","Serbia","贝尔格莱德",""],
  ["Europe/Kaliningrad","RU","俄罗斯","Russia","加里宁格勒",""],
  ["Europe/Moscow","RU","俄罗斯","Russia","莫斯科","W-SU"],
  ["Europe/Simferopol","UA","乌克兰","Ukraine","辛菲罗波尔",""],
  ["Europe/Kirov","RU","俄罗斯","Russia","基洛夫",""],
  ["Europe/Volgograd","RU","俄罗斯","Russia","伏尔加格勒",""],
  ["Europe/Astrakhan","RU","俄罗斯","Russia","阿斯特拉罕",""],
  ["Europe/Saratov","RU","俄罗斯","Russia","萨拉托夫",""],
  ["Europe/Ulyanovsk","RU","俄罗斯","Russia","乌里扬诺夫斯克",""],
  ["Europe/Samara","RU","俄罗斯","Russia","萨马拉",""],
  ["Asia/Yekaterinburg","RU","俄罗斯","Russia","叶卡捷琳堡",""],
  ["Asia/Omsk","RU","俄罗斯","Russia","鄂木斯克",""],
  ["Asia/Novosibirsk","RU","俄罗斯","Russia","新西伯利亚",""],
  ["Asia/Barnaul","RU","俄罗斯","Russia","巴尔瑙尔",""],
  ["Asia/Tomsk","RU","俄罗斯","Russia","托木斯克",""],
  ["Asia/Novokuznetsk","RU","俄罗斯","Russia","新库兹涅茨克",""],
  ["Asia/Krasnoyarsk","RU","俄罗斯","Russia","克拉斯诺亚尔斯克",""],
  ["Asia/Irkutsk","RU","俄罗斯","Russia","伊尔库茨克",""],
  ["Asia/Chita","RU","俄罗斯","Russia","赤塔",""],
  ["Asia/Yakutsk","RU","俄罗斯","Russia","雅库茨克",""],
  ["Asia/Khandyga","RU","俄罗斯","Russia","汉德加",""],
  ["Asia/Vladivostok","RU","俄罗斯","Russia","海参崴",""],
  ["Asia/Ust-Nera","RU","俄罗斯","Russia","乌斯内拉",""],
  ["Asia/Magadan","RU","俄罗斯","Russia","马加丹",""],
  ["Asia/Sakhalin","RU","俄罗斯","Russia","萨哈林",""],
  ["Asia/Srednekolymsk","RU","俄罗斯","Russia","中科雷姆斯克",""],
  ["Asia/Kamchatka","RU","俄罗斯","Russia","堪察加",""],
  ["Asia/Anadyr","RU","俄罗斯","Russia","阿纳德尔",""],
  ["Africa/Kigali","RW","卢旺达","Rwanda","基加利",""],
  ["Asia/Riyadh","SA","沙特阿拉伯","Saudi Arabia","利雅得",""],
  ["Pacific/Guadalcanal","SB","所罗门群岛","Solomon Islands","瓜达尔卡纳尔",""],
  ["Indian/Mahe","SC","塞舌尔","Seychelles","马埃岛",""],
  ["Africa/Khartoum","SD","苏丹","Sudan","喀土穆",""],
  ["Europe/Stockholm","SE","瑞典","Sweden","斯德哥尔摩",""],
  ["Asia/Singapore","SG","新加坡","Singapore","新加坡","Singapore"],
  ["Atlantic/St_Helena","SH","圣赫勒拿","St. Helena","圣赫勒拿",""],
  ["Europe/Ljubljana","SI","斯洛文尼亚","Slovenia","卢布尔雅那",""],
  ["Arctic/Longyearbyen","SJ","斯瓦尔巴和扬马延","Svalbard & Jan Mayen","朗伊尔城","Atlantic/Jan_Mayen"],
  ["Europe/Bratislava","SK","斯洛伐克","Slovakia","布拉迪斯拉发",""],
  ["Africa/Freetown","SL","塞拉利昂","Sierra Leone","弗里敦",""],
  ["Europe/San_Marino","SM","圣马力诺","San Marino","圣马力诺",""],
  ["Africa/Dakar","SN","塞内加尔","Senegal","达喀尔",""],
  ["Africa/Mogadishu","SO","索马里","Somalia","摩加迪沙",""],
  ["America/Paramaribo","SR","苏里南","Suriname","帕拉马里博",""],
  ["Africa/Juba","SS","南苏丹","South Sudan","朱巴",""],
  ["Africa/Sao_Tome","ST","圣多美和普林西比","São Tomé & Príncipe","圣多美",""],
  ["America/El_Salvador","SV","萨尔瓦多","El Salvador","萨尔瓦多",""],
  ["America/Lower_Princes","SX","荷属圣马丁","Sint Maarten","下太子区",""],
  ["Asia/Damascus","SY","叙利亚","Syria","大马士革",""],
  ["Africa/Mbabane","SZ","斯威士兰","Eswatini","姆巴巴纳",""],
  ["America/Grand_Turk","TC","特克斯和凯科斯群岛","Turks & Caicos Islands","大特克",""],
  ["Africa/Ndjamena","TD","乍得","Chad","恩贾梅纳",""],
  ["Indian/Kerguelen","TF","法属南部领地","French Southern Territories","凯尔盖朗",""],
  ["Africa/Lome","TG","多哥","Togo","洛美",""],
  ["Asia/Bangkok","TH","泰国","Thailand","曼谷",""],
  ["Asia/Dushanbe","TJ","塔吉克斯坦","Tajikistan","杜尚别",""],
  ["Pacific/Fakaofo","TK","托克劳","Tokelau","法考福",""],
  ["Asia/Dili","TL","东帝汶","Timor-Leste","帝力",""],
  ["Asia/Ashgabat","TM","土库曼斯坦","Turkmenistan","阿什哈巴德","Asia/Ashkhabad"],
  ["Africa/Tunis","TN","突尼斯","Tunisia","突尼斯",""],
  ["Pacific/Tongatapu","TO","汤加","Tonga","东加塔布",""],
  ["Europe/Istanbul","TR","土耳其","Türkiye","伊斯坦布尔","Asia/Istanbul Turkey"],
  ["America/Port_of_Spain","TT","特立尼达和多巴哥","Trinidad & Tobago","西班牙港",""],
  ["Pacific/Funafuti","TV","图瓦卢","Tuvalu","富纳富提",""],
  ["Asia/Taipei","TW","台湾","Taiwan","台北","ROC"],
  ["Africa/Dar_es_Salaam","TZ","坦桑尼亚","Tanzania","达累斯萨拉姆",""],
  ["Europe/Kyiv","UA","乌克兰","Ukraine","基辅","Europe/Kiev Europe/Zaporozhye Europe/Uzhgorod"],
  ["Africa/Kampala","UG","乌干达","Uganda","坎帕拉",""],
  ["Pacific/Midway","UM","美国本土外小岛屿","U.S. Outlying Islands","中途岛",""],
  ["Pacific/Wake","UM","美国本土外小岛屿","U.S. Outlying Islands","威克",""],
  ["America/New_York","US","美国","United States","纽约","US/Eastern EST5EDT"],
  ["America/Detroit","US","美国","United States","底特律","US/Michigan"],
  ["America/Kentucky/Louisville","US","美国","United States","路易斯维尔","America/Louisville"],
  ["America/Kentucky/Monticello","US","美国","United States","肯塔基州蒙蒂塞洛",""],
  ["America/Indiana/Indianapolis","US","美国","United States","印第安纳波利斯","America/Indianapolis America/Fort_Wayne US/East-Indiana"],
  ["America/Indiana/Vincennes","US","美国","United States","印第安纳州温森斯",""],
  ["America/Indiana/Winamac","US","美国","United States","印第安纳州威纳马克",""],
  ["America/Indiana/Marengo","US","美国","United States","印第安纳州马伦戈",""],
  ["America/Indiana/Petersburg","US","美国","United States","印第安纳州彼得斯堡",""],
  ["America/Indiana/Vevay","US","美国","United States","印第安纳州维维市",""],
  ["America/Chicago","US","美国","United States","芝加哥","US/Central CST6CDT"],
  ["America/Indiana/Tell_City","US","美国","United States","印第安纳州特尔城",""],
  ["America/Indiana/Knox","US","美国","United States","印第安纳州诺克斯","America/Knox_IN US/Indiana-Starke"],
  ["America/Menominee","US","美国","United States","梅诺米尼",""],
  ["America/North_Dakota/Center","US","美国","United States","北达科他州申特",""],
  ["America/North_Dakota/New_Salem","US","美国","United States","北达科他州新塞勒姆",""],
  ["America/North_Dakota/Beulah","US","美国","United States","北达科他州比尤拉",""],
  ["America/Denver","US","美国","United States","丹佛","America/Shiprock Navajo US/Mountain MST7MDT"],
  ["America/Boise","US","美国","United States","博伊西",""],
  ["America/Phoenix","US","美国","United States","凤凰城","US/Arizona MST"],
  ["America/Los_Angeles","US","美国","United States","洛杉矶","US/Pacific US/Pacific-New PST8PDT"],
  ["America/Anchorage","US","美国","United States","安克雷奇","US/Alaska"],
  ["America/Juneau","US","美国","United States","朱诺",""],
  ["America/Sitka","US","美国","United States","锡特卡",""],
  ["America/Metlakatla","US","美国","United States","梅特拉卡特拉",""],
  ["America/Yakutat","US","美国","United States","亚库塔特",""],
  ["America/Nome","US","美国","United States","诺姆",""],
  ["America/Adak","US","美国","United States","埃达克","America/Atka US/Aleutian"],
  ["Pacific/Honolulu","US","美国","United States","檀香山","US/Hawaii Pacific/Johnston HST"],
  ["America/Montevideo","UY","乌拉圭","Uruguay","蒙得维的亚",""],
  ["Asia/Samarkand","UZ","乌兹别克斯坦","Uzbekistan","撒马尔罕",""],
  ["Asia/Tashkent","UZ","乌兹别克斯坦","Uzbekistan","塔什干",""],
  ["Europe/Vatican","VA","梵蒂冈","Vatican City","梵蒂冈",""],
  ["America/St_Vincent","VC","圣文森特和格林纳丁斯","St. Vincent & Grenadines","圣文森特",""],
  ["America/Caracas","VE","委内瑞拉","Venezuela","加拉加斯",""],
  ["America/Tortola","VG","英属维尔京群岛","British Virgin Islands","托尔托拉",""],
  ["America/St_Thomas","VI","美属维尔京群岛","U.S. Virgin Islands","圣托马斯","America/Virgin"],
  ["Asia/Ho_Chi_Minh","VN","越南","Vietnam","胡志明市","Asia/Saigon"],
  ["Pacific/Efate","VU","瓦努阿图","Vanuatu","埃法特",""],
  ["Pacific/Wallis","WF","瓦利斯和富图纳","Wallis & Futuna","瓦利斯",""],
  ["Pacific/Apia","WS","萨摩亚","Samoa","阿皮亚",""],
  ["Asia/Aden","YE","也门","Yemen","亚丁",""],
  ["Indian/Mayotte","YT","马约特","Mayotte","马约特",""],
  ["Africa/Johannesburg","ZA","南非","South Africa","约翰内斯堡",""],
  ["Africa/Lusaka","ZM","赞比亚","Zambia","卢萨卡",""],
  ["Africa/Harare","ZW","津巴布韦","Zimbabwe","哈拉雷",""],
]
